version: '3.8'

services:
  back-end:
    build: ./back-end
    restart: always
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  front-end:
    build: ./front-end
    restart: always
    ports:
      - 3000:3000